service: serverless-example

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  httpApi:
    cors: true

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
